--- 
log4r_config: 
  loggers: 
  - trace: "false"
    additive: "false"
    name: assignments
    level: DEBUG
    outputters: 
    - stderr
    - assignments
  - trace: "false"
    additive: "false"
    name: teams
    level: NONE
    outputters: 
    - stderr
    - teams
  - trace: "false"
    additive: "false"
    name: reviews
    level: NONE
    outputters: 
    - stderr
    - reviews
  - trace: "false"
    additive: "false"
    name: responses
    level: NONE
    outputters: 
    - stderr
    - responses
  outputters: 
  - type: DateFileOutputter
    name: assignments
    filename: assignments.log
    level: DEBUG
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      type: PatternFormatter
      date_pattern: "%Y-%m-%d %H:%M:%S"
      pattern: "%d %l: %m "
  - type: DateFileOutputter
    name: teams
    filename: teams.log
    level: DEBUG
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      type: PatternFormatter
      date_pattern: "%Y-%m-%d %H:%M:%S"
      pattern: "%d %l: %m "
  - type: DateFileOutputter
    name: reviews
    filename: reviews.log
    level: DEBUG
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      type: PatternFormatter
      date_pattern: "%Y-%m-%d %H:%M:%S"
      pattern: "%d %l: %m "
  - type: DateFileOutputter
    name: responses
    filename: responses.log
    level: DEBUG
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      type: PatternFormatter
      date_pattern: "%Y-%m-%d %H:%M:%S"
      pattern: "%d %l: %m "
  - type: StderrOutputter
    name: stderr
    level: DEBUG
    formatter: 
      type: PatternFormatter
      date_pattern: "%Y-%m-%d %H:%M:%S"
      pattern: "%d %l: %m "
  pre_config: 
    custom_levels: 
    - DEBUG
    - INFO
    - NONE
    root: 
      level: DEBUG
    global: 
      level: DEBUG
