--- 
log4r_config: 
  loggers: 
  - level: INFO
    outputters: 
    - stderr
    - assignments
    trace: "false"
    additive: "false"
    name: assignments
  - level: NONE
    outputters: 
    - stderr
    - teams
    trace: "false"
    additive: "false"
    name: teams
  - level: NONE
    outputters: 
    - stderr
    - reviews
    trace: "false"
    additive: "false"
    name: reviews
  - level: NONE
    outputters: 
    - stderr
    - responses
    trace: "false"
    additive: "false"
    name: responses
  - level: INFO
    outputters: 
    - stderr
    - topics
    trace: "false"
    additive: "false"
    name: topics
  outputters: 
  - filename: assignments.log
    level: DEBUG
    type: DateFileOutputter
    formatter: 
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
      pattern: "%d %l: %m "
    dirname: "#{RAILS_ROOT}/log"
    name: assignments
  - filename: teams.log
    level: DEBUG
    type: DateFileOutputter
    formatter: 
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
      pattern: "%d %l: %m "
    dirname: "#{RAILS_ROOT}/log"
    name: teams
  - filename: reviews.log
    level: DEBUG
    type: DateFileOutputter
    formatter: 
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
      pattern: "%d %l: %m "
    dirname: "#{RAILS_ROOT}/log"
    name: reviews
  - filename: responses.log
    level: DEBUG
    type: DateFileOutputter
    formatter: 
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
      pattern: "%d %l: %m "
    dirname: "#{RAILS_ROOT}/log"
    name: responses
  - filename: topics.log
    level: DEBUG
    type: DateFileOutputter
    formatter: 
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
      pattern: "%d %l: %m "
    dirname: "#{RAILS_ROOT}/log"
    name: topics
  - level: DEBUG
    type: StderrOutputter
    formatter: 
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
      pattern: "%d %l: %m "
    name: stderr
  pre_config: 
    global: 
      level: DEBUG
    root: 
      level: DEBUG
    custom_levels: 
    - DEBUG
    - INFO
    - NONE
