--- 
log4r_config: 
  outputters: 
  - level: DEBUG
    filename: assignment.log
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      pattern: "%d %l: %m "
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
    type: DateFileOutputter
    name: assignment
  - level: DEBUG
    filename: team.log
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      pattern: "%d %l: %m "
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
    type: DateFileOutputter
    name: team
  - level: DEBUG
    filename: review.log
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      pattern: "%d %l: %m "
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
    type: DateFileOutputter
    name: review
  - level: DEBUG
    filename: responses.log
    dirname: "#{RAILS_ROOT}/log"
    formatter: 
      pattern: "%d %l: %m "
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
    type: DateFileOutputter
    name: responses
  - level: DEBUG
    formatter: 
      pattern: "%d %l: %m "
      date_pattern: "%Y-%m-%d %H:%M:%S"
      type: PatternFormatter
    type: StderrOutputter
    name: stderr
  pre_config: 
    global: 
      level: DEBUG
    root: 
      level: DEBUG
    custom_levels: 
    - DEBUG
    - INFO
    - NONE
  loggers: 
  - level: NONE
    outputters: 
    - stderr
    - assignment
    additive: "false"
    name: assignment
    trace: "false"
  - level: NONE
    outputters: 
    - stderr
    - team
    additive: "false"
    name: team
    trace: "false"
  - level: NONE
    outputters: 
    - stderr
    - review
    additive: "false"
    name: review
    trace: "false"
  - level: NONE
    outputters: 
    - stderr
    - responses
    additive: "false"
    name: responses
    trace: "false"
