--- 
log4r_config: 
  loggers: 
  - level: INFO
    trace: "false"
    outputters: 
    - stderr
    - assignment
    additive: "false"
    name: assignment
  - level: NONE
    trace: "false"
    outputters: 
    - stderr
    - team
    additive: "false"
    name: team
  - level: NONE
    trace: "false"
    outputters: 
    - stderr
    - review
    additive: "false"
    name: review
  - level: NONE
    trace: "false"
    outputters: 
    - stderr
    - responses
    additive: "false"
    name: responses
  pre_config: 
    root: 
      level: DEBUG
    global: 
      level: DEBUG
    custom_levels: 
    - DEBUG
    - INFO
    - NONE
  outputters: 
  - dirname: "#{RAILS_ROOT}/log"
    filename: assignment.log
    formatter: 
      pattern: "%d %l: %m "
      type: PatternFormatter
      date_pattern: "%y%m%d %H:%M:%S"
    level: DEBUG
    type: DateFileOutputter
    name: assignment
  - dirname: "#{RAILS_ROOT}/log"
    filename: team.log
    formatter: 
      pattern: "%d %l: %m "
      type: PatternFormatter
      date_pattern: "%y%m%d %H:%M:%S"
    level: DEBUG
    type: DateFileOutputter
    name: team
  - dirname: "#{RAILS_ROOT}/log"
    filename: review.log
    formatter: 
      pattern: "%d %l: %m "
      type: PatternFormatter
      date_pattern: "%y%m%d %H:%M:%S"
    level: DEBUG
    type: DateFileOutputter
    name: review
  - dirname: "#{RAILS_ROOT}/log"
    filename: responses.log
    formatter: 
      pattern: "%d %l: %m "
      type: PatternFormatter
      date_pattern: "%y%m%d %H:%M:%S"
    level: DEBUG
    type: DateFileOutputter
    name: responses
  - formatter: 
      pattern: "%d %l: %m "
      type: PatternFormatter
      date_pattern: "%y%m%d %H:%M:%S"
    level: DEBUG
    type: StderrOutputter
    name: stderr
